[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"